apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springdemo
  template:
    metadata:
      labels:
        app: springdemo
    spec:
      containers:
      - name: springdemo-container
        image: pma4acr.azurecr.io/springdemo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springdemo-service
spec:
  selector:
    app: springdemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP