apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springdemo-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springdemo-service
                port:
                  number: 80
