name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
#    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or whatever version your project uses
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar  # or update if using Gradle

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: backendtest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
